export const TAKE_DMG = 'TAKE_DMG'
export const ENEMY_TAKE_DMG = 'ENEMY_TAKE_DMG'
export const ADD_LOOT = 'ADD_LOOT'
export const ENEMY_ADD_LOOT = 'ENEMY_ADD_LOOT'
export const GAIN_XP = 'GAIN_XP'
export const SET_PLAYER = 'SET_PLAYER'
export const SET_ENEMY = 'SET_ENEMY'
export const SET_ENEMY_STATS = 'SET_ENEMY_STATS'